// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7oZ2OOoRvsG7Do0kvoMOWwZa-mh7wuNI',
    appId: '1:830185290805:web:9a46f89ad40ba8a7be457c',
    messagingSenderId: '830185290805',
    projectId: 'prak10-aff83',
    authDomain: 'prak10-aff83.firebaseapp.com',
    storageBucket: 'prak10-aff83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2qKS5uI2ZVqYe3OUpXZ9xty-M3eJnxkg',
    appId: '1:830185290805:android:41d2f26900b51403be457c',
    messagingSenderId: '830185290805',
    projectId: 'prak10-aff83',
    storageBucket: 'prak10-aff83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD37-4aKjNIpwR6AFd0jX3h987LTs8donY',
    appId: '1:830185290805:ios:fb363a1bf8bc4b96be457c',
    messagingSenderId: '830185290805',
    projectId: 'prak10-aff83',
    storageBucket: 'prak10-aff83.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD37-4aKjNIpwR6AFd0jX3h987LTs8donY',
    appId: '1:830185290805:ios:fb363a1bf8bc4b96be457c',
    messagingSenderId: '830185290805',
    projectId: 'prak10-aff83',
    storageBucket: 'prak10-aff83.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
